Ddcnl 8622
hmrc/feedback-frontend pull request #136
Opened 2024-02-22 15:09 UTC by vinnicombe

2024-02-22 16:43 UTC, brian-digital requested changes
sorry, being a little bit pedantic

2024-02-22 16:43 UTC, brian-digital commented on app/forms/QuestionsFormProvider.scala
> +        "whyGiveAnswer"     -> optional(Forms.text.verifying(maxLength(maxFieldSizeWhyGiveScore, "whyGiveAnswer.error.maxlength"))),
being very pedantic but can `maxFieldSizeWhyGiveScore` be renamed `maxFieldSizeWhyGiveAnswer`

2024-02-22 18:36 UTC, vinnicombe commented on app/forms/QuestionsFormProvider.scala
> +        "whyGiveAnswer"     -> optional(Forms.text.verifying(maxLength(maxFieldSizeWhyGiveScore, "whyGiveAnswer.error.maxlength"))),
Good spot! Actioned

2024-02-23 07:26 UTC, brian-digital approved these changes

2024-02-23 07:32 UTC, merged